<?php require 'templates/header.phtml'; ?>
    
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        Cargar categoría
                    </div>
                    <div class="card-body">
                        <form action="addCategory" method="POST">
                            <div class="form-group">
                                <label>Nombre:</label>
                                <input required name="name" type="text" class="form-control" placeholder="Ingrese el nombre de la categoría">
                            </div>
                            <button type="submit" class="btn btn-primary mt-2">Guardar categoría</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card mt-2">
        <div class="card-header">
            Categorías
        </div>
        <div class="card-body">
            <ul class="list-group mt-3">
            <?php foreach($categories as $category): ?>
                <li class="list-group-item item-task">
                    <div>
                        <b><?= $category->name?></b> | (Id: <?= $category->category_id ?>)
                    </div>
                    <div class="actions">
                        <a href="deleteCategory/<?=$category->category_id?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                    </div>
                    <div class="actions">
                        <a href="updateCategoryForm/<?=$category->category_id?>" type="button" class='btn btn-warning my-2'>Modificar</a>
                    </div>
                </li>
            <?php endforeach ?>
            </ul>
        </div>
    </div>

<?php require 'templates/footer.phtml' ?>