<?php require 'templates/header.phtml' ?>

<div class="container d-flex flex-column justify-content-center align-items-center">
    <h1 class="h3">Listado de Categorías</h1>
    <?php foreach($categories as $category): ?>
        <div class="w-50 m-2 card d-flex flex-row justify-content-between align-items-center px-2">
                <div class="w-50 m-3">
                    <h2 class="card-title h5"><?=$category->name?></h2>
                </div>
                <a href="category/<?=$category->category_id?>" class="btn btn-info">Ver productos</a>
        </div>
    <?php endforeach ?>
</div>

<?php require 'templates/footer.phtml' ?>