<?php require 'templates/header.phtml'; ?>
    
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        Cargar Producto
                    </div>
                    <div class="card-body">
                        <form action="addProduct" method="POST">
                            <div class="form-group">
                                <label>Nombre:</label>
                                <input required name="name" type="text" class="form-control" placeholder="Ingrese el nombre del producto">
                            </div>
                            <div class="form-group">
                                <label>Descripción:</label>
                                <textarea required name="description" class="form-control" rows="3" placeholder="Ingrese la descripción del producto"></textarea>
                            </div>
                            <div class="form-group">
                                <label>Precio:</label>
                                <input required name="price" type="number" class="form-control" placeholder="Ingrese el precio del producto">
                            </div>
                            <div class="form-group">
                                <label>Stock:</label>
                                <input required name="stock" type="number" class="form-control" placeholder="Ingrese el stock del producto">
                            </div>
                            <div class="form-group">
                                <label>Categoría:</label>
                                <select name="category" class="form-control">
                                    <?php foreach($categories as $category): ?>
                                        <option value="<?=$category->category_id?>"><?=$category->name?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary mt-2">Guardar Producto</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card mt-2">
        <div class="card-header">
            Productos
        </div>
        <div class="card-body">
            <ul class="list-group mt-3">
            <?php foreach($products as $product): ?>
                <li class="list-group-item item-task">
                    <div>
                        <b><?= $product->name?></b> | (Id: <?= $product->product_id ?>)
                    </div>
                    <div class="actions">
                        <a href="deleteProduct/<?=$product->product_id?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                    </div>
                    <div class="actions">
                        <a href="updateProductForm/<?=$product->product_id?>" type="button" class='btn btn-warning my-2'>Modificar</a>
                    </div>
                </li>
            <?php endforeach ?>
            </ul>
        </div>
    </div>

<?php require 'templates/footer.phtml' ?>