<?php require 'templates/header.phtml' ?>

<div class="container mt-5">
    <h1 class="h3">Listado de Productos</h1>
    <div class="row">
        <?php foreach($products as $product): ?>
            <div class="col-md-3 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title h5"><?=$product->name?></h2>
                        <h3 class="card-title h6"><?=$product->category?></h3>
                        <p class="card-text"><?=$product->description?></p>
                        <a href="product/<?=$product->product_id?>" class="btn btn-info">Más información</a>
                    </div>
                </div>
            </div>    
        <?php endforeach ?>
    </div> 
</div> 

<?php require 'templates/footer.phtml' ?>