<?php require 'templates/header.phtml'; ?>
    
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        Modificar producto
                    </div>
                    <div class="card-body">
                        <form action="updateProduct/<?=$id?>" method="POST">
                            <div class="form-group">
                                <label>Nombre:</label>
                                <input required name="name" type="text" class="form-control" placeholder="Ingrese el nombre del producto">
                            </div>
                            <div class="form-group">
                                <label>Descripción:</label>
                                <textarea required name="description" class="form-control" rows="3" placeholder="Ingrese la descripción del producto"></textarea>
                            </div>
                            <div class="form-group">
                                <label>Precio:</label>
                                <input required name="price" type="number" class="form-control" placeholder="Ingrese el precio del producto">
                            </div>
                            <div class="form-group">
                                <label>Stock:</label>
                                <input required name="stock" type="number" class="form-control" placeholder="Ingrese el stock del producto">
                            </div>
                            <div class="form-group">
                                <label>Categoría:</label>
                                <select name="category" class="form-control">
                                    <?php foreach($categories as $category): ?>
                                        <option value="<?=$category->category_id?>"><?=$category->name?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary mt-2">Modificar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php require 'templates/footer.phtml' ?>