<?php require 'templates/header.phtml' ?>

<div class="container">
    <h1 class="h3">Detalles del Producto</h1>
    <div class="row">
        <div class="col-md-6">
            <h2 class="h4"><?=$product->name?></h2>
                <h3 class="h6">Descripción</h3>
                    <p><?=$product->description?></p>
        </div>
        <div class="col-md-6">
                <h3 class="h6">Precio</h3>
                    <p>$<?=$product->price?></p>
                <h3 class="h6">Stock</h3>
                    <p><?=$product->stock?></p>
                <h3 class="h6">Marca</h3>
                    <p><?=$product->brand_id?></p>
                <h3 class="h6">Categoría</h3>
                    <p><?=$product->category_id?></p>
        </div>
    </div>
</div>

<?php require 'templates/footer.phtml' ?>